"""add proxy model

Revision ID: 1d4936846fed
Revises: agregar_next_cycle_at
Create Date: 2026-02-04 02:38:40.286145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4936846fed'
down_revision = 'agregar_next_cycle_at'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear tabla proxies si no existe
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    if 'proxies' not in existing_tables:
        op.create_table('proxies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('host', sa.String(length=255), nullable=False),
        sa.Column('port', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('kind', sa.Enum('DATAIMPULSE', 'UNKNOWN', name='proxykind'), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=True),
        sa.Column('password', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    
    # Crear índice solo si no existe
    if 'email' in existing_tables:
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('email')]
        if 'idx_email_usage_count' not in existing_indexes:
            with op.batch_alter_table('email', schema=None) as batch_op:
                batch_op.create_index('idx_email_usage_count', ['usage_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_index('idx_email_usage_count')

    op.drop_table('proxies')
    # ### end Alembic commands ###
