"""crear_tabla_email

Revision ID: 7adac5c2-b7c
Revises: ce8602a595ab
Create Date: 2025-10-01 06:15:01.780176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7adac5c2b7c'
down_revision = 'ce8602a595ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar si la tabla ya existe antes de crearla
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    if 'email' not in existing_tables:
        op.create_table('email',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        print("Tabla 'email' creada")
        
        # Crear índices solo si la tabla se creó
        op.create_index('idx_email_created', 'email', ['created_at'], unique=False)
        op.create_index('idx_email_user_created', 'email', ['user_id', 'created_at'], unique=False)
        op.create_index('idx_email_user_id', 'email', ['user_id'], unique=False)
        print("Índices de la tabla 'email' creados")
    else:
        print("Tabla 'email' ya existe, saltando creación")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar si la tabla existe antes de eliminarla
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    if 'email' in existing_tables:
        op.drop_index('idx_email_user_id', table_name='email')
        op.drop_index('idx_email_user_created', table_name='email')
        op.drop_index('idx_email_created', table_name='email')
        op.drop_table('email')
        print("Tabla 'email' eliminada")
    else:
        print("Tabla 'email' no existe, saltando eliminación")
    # ### end Alembic commands ###
