"""eliminar_product_types_de_vps

Revision ID: 918abd894d94
Revises: 9b79358b6c2a
Create Date: 2026-03-14 22:46:54.575053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918abd894d94'
down_revision = '9b79358b6c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vps', schema=None) as batch_op:
        batch_op.drop_column('product_types')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_types', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
