"""agregar_product_types_a_vps

Revision ID: 9b79358b6c2a
Revises: 19f935c09cfd
Create Date: 2026-03-14 22:33:50.175256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b79358b6c2a'
down_revision = '19f935c09cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_types', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vps', schema=None) as batch_op:
        batch_op.drop_column('product_types')

    # ### end Alembic commands ###
