"""actualizar_emails_2_usos_a_completed

Revision ID: actualizar_emails_2_usos_a_completed
Revises: ce8602a595ab
Create Date: 2025-01-08 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'actualizar_emails_2_usos_a_completed'
down_revision = 'ce8602a595ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar si la tabla existe
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    if 'email' in existing_tables:
        # Verificar si las columnas existen
        existing_columns = [col['name'] for col in inspector.get_columns('email')]
        
        if 'usage_count' in existing_columns and 'status' in existing_columns:
            # Actualizar emails con usage_count = 2 y status = 'active' a status = 'completed'
            result = connection.execute(
                sa.text("""
                    UPDATE email 
                    SET status = 'completed' 
                    WHERE usage_count = 2 AND status = 'active'
                """)
            )
            
            updated_count = result.rowcount
            print(f"Se actualizaron {updated_count} emails de status 'active' a 'completed' (emails con 2 usos)")
            
            # Mostrar estadísticas después de la actualización
            stats_result = connection.execute(
                sa.text("""
                    SELECT 
                        status,
                        usage_count,
                        COUNT(*) as count
                    FROM email 
                    GROUP BY status, usage_count
                    ORDER BY status, usage_count
                """)
            )
            
            print("\nEstadísticas después de la actualización:")
            for row in stats_result:
                print(f"  Status: {row.status}, Usage Count: {row.usage_count}, Count: {row.count}")
        else:
            print("Las columnas 'usage_count' o 'status' no existen en la tabla 'email'")
    else:
        print("Tabla 'email' no existe, saltando actualización")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar si la tabla existe
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    if 'email' in existing_tables:
        # Verificar si las columnas existen
        existing_columns = [col['name'] for col in inspector.get_columns('email')]
        
        if 'usage_count' in existing_columns and 'status' in existing_columns:
            # Revertir emails con usage_count = 2 y status = 'completed' a status = 'active'
            result = connection.execute(
                sa.text("""
                    UPDATE email 
                    SET status = 'active' 
                    WHERE usage_count = 2 AND status = 'completed'
                """)
            )
            
            reverted_count = result.rowcount
            print(f"Se revirtieron {reverted_count} emails de status 'completed' a 'active' (emails con 2 usos)")
            
            # Mostrar estadísticas después de la reversión
            stats_result = connection.execute(
                sa.text("""
                    SELECT 
                        status,
                        usage_count,
                        COUNT(*) as count
                    FROM email 
                    GROUP BY status, usage_count
                    ORDER BY status, usage_count
                """)
            )
            
            print("\nEstadísticas después de la reversión:")
            for row in stats_result:
                print(f"  Status: {row.status}, Usage Count: {row.usage_count}, Count: {row.count}")
        else:
            print("Las columnas 'usage_count' o 'status' no existen en la tabla 'email'")
    else:
        print("Tabla 'email' no existe, saltando reversión")
    # ### end Alembic commands ###
