"""actualizar_emails_2_usos_a_completed

Revision ID: actualizar_emails_2_usos_a_completed
Revises: ce8602a595ab
Create Date: 2025-01-08 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'actualizar_emails_2_usos_a_completed'
down_revision = 'ce8602a595ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("🚀 Iniciando migración: actualizar emails con 2 usos a completed...")
    
    # Verificar si la tabla existe
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    if 'email' in existing_tables:
        # Verificar si las columnas existen
        existing_columns = [col['name'] for col in inspector.get_columns('email')]
        
        if 'usage_count' in existing_columns and 'status' in existing_columns:
            print("✅ Tabla 'email' encontrada con columnas 'usage_count' y 'status'")
            
            # Mostrar estadísticas ANTES de la actualización
            print("\n📊 Estadísticas ANTES de la actualización:")
            stats_before = connection.execute(
                sa.text("""
                    SELECT 
                        status,
                        usage_count,
                        COUNT(*) as count
                    FROM email 
                    GROUP BY status, usage_count
                    ORDER BY status, usage_count
                """)
            )
            
            for row in stats_before:
                print(f"  Status: {row.status}, Usage Count: {row.usage_count}, Count: {row.count}")
            
            # Contar emails que necesitan corrección
            count_query = connection.execute(
                sa.text("""
                    SELECT COUNT(*) as count
                    FROM email 
                    WHERE usage_count = 2 AND status = 'active'
                """)
            )
            
            emails_to_fix = count_query.fetchone().count
            print(f"\n🔍 Se encontraron {emails_to_fix} emails con usage_count = 2 y status = 'active'")
            
            if emails_to_fix > 0:
                # Actualizar emails con usage_count = 2 y status = 'active' a status = 'completed'
                print("🔄 Actualizando emails...")
                result = connection.execute(
                    sa.text("""
                        UPDATE email 
                        SET status = 'completed' 
                        WHERE usage_count = 2 AND status = 'active'
                    """)
                )
                
                updated_count = result.rowcount
                print(f"✅ Se actualizaron {updated_count} emails de status 'active' a 'completed'")
                
                # Mostrar estadísticas DESPUÉS de la actualización
                print("\n📊 Estadísticas DESPUÉS de la actualización:")
                stats_after = connection.execute(
                    sa.text("""
                        SELECT 
                            status,
                            usage_count,
                            COUNT(*) as count
                        FROM email 
                        GROUP BY status, usage_count
                        ORDER BY status, usage_count
                    """)
                )
                
                for row in stats_after:
                    print(f"  Status: {row.status}, Usage Count: {row.usage_count}, Count: {row.count}")
                
                # Verificar que no queden emails incorrectos
                verify_query = connection.execute(
                    sa.text("""
                        SELECT COUNT(*) as count
                        FROM email 
                        WHERE usage_count = 2 AND status = 'active'
                    """)
                )
                
                remaining_incorrect = verify_query.fetchone().count
                
                if remaining_incorrect == 0:
                    print("\n🎉 ¡Migración completada exitosamente! No quedan emails incorrectos.")
                else:
                    print(f"\n⚠️  Advertencia: Aún quedan {remaining_incorrect} emails con status incorrecto.")
            else:
                print("✅ No hay emails que corregir. Todo está bien.")
        else:
            print("❌ Las columnas 'usage_count' o 'status' no existen en la tabla 'email'")
    else:
        print("❌ Tabla 'email' no existe, saltando actualización")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("🔄 Revirtiendo migración: emails con 2 usos de completed a active...")
    
    # Verificar si la tabla existe
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    if 'email' in existing_tables:
        # Verificar si las columnas existen
        existing_columns = [col['name'] for col in inspector.get_columns('email')]
        
        if 'usage_count' in existing_columns and 'status' in existing_columns:
            print("✅ Tabla 'email' encontrada con columnas 'usage_count' y 'status'")
            
            # Contar emails que necesitan reversión
            count_query = connection.execute(
                sa.text("""
                    SELECT COUNT(*) as count
                    FROM email 
                    WHERE usage_count = 2 AND status = 'completed'
                """)
            )
            
            emails_to_revert = count_query.fetchone().count
            print(f"🔍 Se encontraron {emails_to_revert} emails con usage_count = 2 y status = 'completed'")
            
            if emails_to_revert > 0:
                # Revertir emails con usage_count = 2 y status = 'completed' a status = 'active'
                print("🔄 Revirtiendo emails...")
                result = connection.execute(
                    sa.text("""
                        UPDATE email 
                        SET status = 'active' 
                        WHERE usage_count = 2 AND status = 'completed'
                    """)
                )
                
                reverted_count = result.rowcount
                print(f"✅ Se revirtieron {reverted_count} emails de status 'completed' a 'active'")
                
                # Mostrar estadísticas después de la reversión
                print("\n📊 Estadísticas después de la reversión:")
                stats_result = connection.execute(
                    sa.text("""
                        SELECT 
                            status,
                            usage_count,
                            COUNT(*) as count
                        FROM email 
                        GROUP BY status, usage_count
                        ORDER BY status, usage_count
                    """)
                )
                
                for row in stats_result:
                    print(f"  Status: {row.status}, Usage Count: {row.usage_count}, Count: {row.count}")
            else:
                print("✅ No hay emails que revertir. Todo está bien.")
        else:
            print("❌ Las columnas 'usage_count' o 'status' no existen en la tabla 'email'")
    else:
        print("❌ Tabla 'email' no existe, saltando reversión")
    # ### end Alembic commands ###
