"""agregar_campos_usage_count_y_status_a_emails

Revision ID: agregar_campos_usage_count_y_status_a_emails
Revises: 7adac5c2b7c
Create Date: 2025-01-08 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'agregar_campos_usage_count_y_status_a_emails'
down_revision = '7adac5c2b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar si la tabla existe
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    if 'email' in existing_tables:
        # Verificar si las columnas ya existen
        existing_columns = [col['name'] for col in inspector.get_columns('email')]
        
        # Agregar columna usage_count si no existe
        if 'usage_count' not in existing_columns:
            op.add_column('email', sa.Column('usage_count', sa.Integer(), nullable=False, server_default='0'))
            print("Columna 'usage_count' agregada a la tabla 'email'")
        else:
            print("Columna 'usage_count' ya existe en la tabla 'email'")
        
        # Agregar columna status si no existe
        if 'status' not in existing_columns:
            op.add_column('email', sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
            print("Columna 'status' agregada a la tabla 'email'")
        else:
            print("Columna 'status' ya existe en la tabla 'email'")
        
        # Crear nuevos índices si no existen
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('email')]
        
        if 'idx_email_status' not in existing_indexes:
            op.create_index('idx_email_status', 'email', ['status'], unique=False)
            print("Índice 'idx_email_status' creado")
        
        if 'idx_email_user_status_usage_created' not in existing_indexes:
            op.create_index('idx_email_user_status_usage_created', 'email', ['user_id', 'status', 'usage_count', 'created_at'], unique=False)
            print("Índice 'idx_email_user_status_usage_created' creado")
        
        # Eliminar índices antiguos si existen y crear los nuevos
        if 'idx_email_user_created' in existing_indexes:
            op.drop_index('idx_email_user_created', table_name='email')
            print("Índice 'idx_email_user_created' eliminado")
    else:
        print("Tabla 'email' no existe, saltando modificación")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar si la tabla existe
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    if 'email' in existing_tables:
        # Verificar si las columnas existen
        existing_columns = [col['name'] for col in inspector.get_columns('email')]
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('email')]
        
        # Eliminar índices nuevos
        if 'idx_email_user_status_usage_created' in existing_indexes:
            op.drop_index('idx_email_user_status_usage_created', table_name='email')
            print("Índice 'idx_email_user_status_usage_created' eliminado")
        
        if 'idx_email_status' in existing_indexes:
            op.drop_index('idx_email_status', table_name='email')
            print("Índice 'idx_email_status' eliminado")
        
        # Recrear índice antiguo
        if 'idx_email_user_created' not in existing_indexes:
            op.create_index('idx_email_user_created', 'email', ['user_id', 'created_at'], unique=False)
            print("Índice 'idx_email_user_created' recreado")
        
        # Eliminar columnas
        if 'status' in existing_columns:
            op.drop_column('email', 'status')
            print("Columna 'status' eliminada de la tabla 'email'")
        
        if 'usage_count' in existing_columns:
            op.drop_column('email', 'usage_count')
            print("Columna 'usage_count' eliminada de la tabla 'email'")
    else:
        print("Tabla 'email' no existe, saltando reversión")
    # ### end Alembic commands ###
