"""crear_tabla_bot

Revision ID: crear_tabla_bot
Revises: merge_heads_accounts_y_emails
Create Date: 2026-01-21 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'crear_tabla_bot'
down_revision = 'merge_heads_accounts_y_emails'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar si la tabla ya existe antes de crearla
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    if 'bot' not in existing_tables:
        op.create_table('bot',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('bot_type', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='offline'),
        sa.Column('socket_id', sa.String(length=100), nullable=True),
        sa.Column('last_seen', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        print("Tabla 'bot' creada")
        
        # Crear índices
        op.create_index('idx_bot_user_id', 'bot', ['user_id'], unique=False)
        op.create_index('idx_bot_status', 'bot', ['status'], unique=False)
        op.create_index('idx_bot_socket_id', 'bot', ['socket_id'], unique=False)
        print("Índices de la tabla 'bot' creados")
    else:
        print("Tabla 'bot' ya existe, saltando creación")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar si la tabla existe antes de eliminarla
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    if 'bot' in existing_tables:
        op.drop_index('idx_bot_socket_id', table_name='bot')
        op.drop_index('idx_bot_status', table_name='bot')
        op.drop_index('idx_bot_user_id', table_name='bot')
        op.drop_table('bot')
        print("Tabla 'bot' eliminada")
    else:
        print("Tabla 'bot' no existe, saltando eliminación")
    # ### end Alembic commands ###

